# Generated by Django 5.2.7 on 2025-10-08 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expertise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        help_text="e.g., 'bi bi-gear-wide-connected'", max_length=100
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="GeneralInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Your name for the navbar logo and footer.",
                        max_length=100,
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        help_text="Upload your resume PDF file.",
                        null=True,
                        upload_to="resumes/",
                    ),
                ),
                (
                    "hero_title",
                    models.TextField(
                        default="Building digital<br><span class='gradient-text'>experiences</span> that matter"
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Full-stack developer crafting beautiful, accessible, and performant web applications with modern technologies."
                    ),
                ),
                (
                    "about_section_tag",
                    models.CharField(default="About Me", max_length=50),
                ),
                (
                    "about_title",
                    models.CharField(
                        default="Crafting Digital Solutions", max_length=200
                    ),
                ),
                (
                    "about_subtitle",
                    models.TextField(
                        default="Passionate about creating innovative web experiences that combine beautiful design with powerful functionality"
                    ),
                ),
                (
                    "about_image",
                    models.ImageField(
                        help_text="Upload your professional headshot.",
                        upload_to="profile_images/",
                    ),
                ),
                (
                    "about_content_title",
                    models.CharField(
                        default="Hello! I'm a developer who loves building things for the web.",
                        max_length=200,
                    ),
                ),
                (
                    "about_content_p1",
                    models.TextField(
                        default="My journey in web development started years ago..."
                    ),
                ),
                (
                    "about_content_p2",
                    models.TextField(
                        default="Currently, I'm focused on building innovative products..."
                    ),
                ),
                ("projects_completed", models.CharField(default="50+", max_length=10)),
                ("happy_clients", models.CharField(default="30+", max_length=10)),
                ("years_experience", models.CharField(default="3+", max_length=10)),
                (
                    "skills_section_tag",
                    models.CharField(default="Skills", max_length=50),
                ),
                (
                    "skills_title",
                    models.CharField(default="My Capabilities", max_length=200),
                ),
                (
                    "skills_subtitle",
                    models.TextField(
                        default="A blend of modern technologies and core software engineering expertise."
                    ),
                ),
                (
                    "projects_section_tag",
                    models.CharField(default="Projects", max_length=50),
                ),
                (
                    "projects_title",
                    models.CharField(default="My Projects", max_length=200),
                ),
                (
                    "projects_subtitle",
                    models.TextField(
                        default="A collection of my work. Use the filters to explore different categories."
                    ),
                ),
                (
                    "contact_section_tag",
                    models.CharField(default="Contact", max_length=50),
                ),
                (
                    "contact_title",
                    models.CharField(
                        default="Let's Build Something Amazing", max_length=200
                    ),
                ),
                (
                    "contact_text_title",
                    models.CharField(
                        default="Have a project in mind or just want to connect? My inbox is always open.",
                        max_length=200,
                    ),
                ),
                (
                    "contact_text_subtitle",
                    models.TextField(
                        default="I'm currently available for freelance opportunities..."
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(default="youremail@example.com", max_length=254),
                ),
                (
                    "footer_text",
                    models.CharField(
                        default="Designed & Built by Your Name", max_length=100
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "General Info",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="project_images/")),
                ("github_link", models.URLField(blank=True, null=True)),
                ("live_demo_link", models.URLField(blank=True, null=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this project should appear in the 'Featured' tab.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the name. Auto-generated if left blank.",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Project Categories",
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the name. Auto-generated if left blank.",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(help_text="e.g., GitHub, LinkedIn", max_length=50),
                ),
                (
                    "icon_class",
                    models.CharField(help_text="e.g., 'bi bi-github'", max_length=100),
                ),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClickEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("RESUME_DOWNLOAD", "Resume Download"),
                            ("PROJECT_LIVE_DEMO", "Project Live Demo"),
                            ("PROJECT_GITHUB", "Project GitHub"),
                            ("EMAIL_CLICK", "Email Click"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "details",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Project ID or other info",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="click_events",
                        to="portfolio.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="categories",
            field=models.ManyToManyField(
                related_name="projects", to="portfolio.projectcategory"
            ),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "icon_class",
                    models.CharField(
                        help_text="e.g., 'bi bi-filetype-html'", max_length=100
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="portfolio.skillcategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(related_name="projects", to="portfolio.tag"),
        ),
    ]
