# Generated by Django 5.2.7 on 2025-10-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("organization", models.CharField(max_length=200)),
                ("date_issued", models.DateField()),
                (
                    "credential_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the credential verification page.",
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload a logo or image for the certification.",
                        upload_to="cert_images/",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Set display order (lower numbers show first).",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-date_issued"],
            },
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="certifications_section_tag",
            field=models.CharField(default="Certifications", max_length=50),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="certifications_subtitle",
            field=models.TextField(
                default="A showcase of my credentials and professional qualifications."
            ),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="certifications_title",
            field=models.CharField(default="Licenses & Certifications", max_length=200),
        ),
    ]
