# Generated by Django 5.2.7 on 2025-10-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expertise",
            name="icon_class",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="icon_class",
        ),
        migrations.RemoveField(
            model_name="sociallink",
            name="icon_class",
        ),
        migrations.AddField(
            model_name="expertise",
            name="svg_icon_code",
            field=models.TextField(
                blank=True, help_text="Paste the full SVG code for the icon.", null=True
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="svg_icon_code",
            field=models.TextField(
                blank=True, help_text="Paste the full SVG code for the icon.", null=True
            ),
        ),
        migrations.AddField(
            model_name="sociallink",
            name="svg_icon_code",
            field=models.TextField(
                blank=True, help_text="Paste the SVG code from Simple Icons.", null=True
            ),
        ),
    ]
