# Generated by Django 5.2.7 on 2025-10-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0002_certification_generalinfo_certifications_section_tag_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("organization", models.CharField(max_length=200)),
                ("date_issued", models.DateField()),
                (
                    "credential_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the credential verification page.",
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload a logo or image for the license.",
                        upload_to="license_images/",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Set display order (lower numbers show first).",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-date_issued"],
            },
        ),
        migrations.CreateModel(
            name="LicenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly version of the name. Auto-generated.",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "License Categories",
            },
        ),
        migrations.DeleteModel(
            name="Certification",
        ),
        migrations.RenameField(
            model_name="generalinfo",
            old_name="certifications_subtitle",
            new_name="licenses_subtitle",
        ),
        migrations.RemoveField(
            model_name="generalinfo",
            name="certifications_section_tag",
        ),
        migrations.RemoveField(
            model_name="generalinfo",
            name="certifications_title",
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="licenses_section_tag",
            field=models.CharField(default="Licenses", max_length=50),
        ),
        migrations.AddField(
            model_name="generalinfo",
            name="licenses_title",
            field=models.CharField(default="Licenses & Certifications", max_length=200),
        ),
        migrations.AddField(
            model_name="license",
            name="categories",
            field=models.ManyToManyField(
                related_name="licenses", to="portfolio.licensecategory"
            ),
        ),
    ]
