# Generated by Django 5.2.7 on 2025-10-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_license_licensecategory_delete_certification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClickEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("RESUME_DOWNLOAD", "Resume Download"),
                            ("PROJECT_LIVE_DEMO", "Project Live Demo"),
                            ("PROJECT_GITHUB", "Project GitHub"),
                            ("EMAIL_CLICK", "Email Click"),
                            ("LICENSE_VIEW", "License View"),
                        ],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "details",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Project ID or License Title",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
