# Generated by Django 5.2.7 on 2025-10-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_clickevent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalinfo",
            name="licenses_section_tag",
        ),
        migrations.RemoveField(
            model_name="generalinfo",
            name="licenses_subtitle",
        ),
        migrations.RemoveField(
            model_name="generalinfo",
            name="licenses_title",
        ),
        migrations.AlterField(
            model_name="clickevent",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("RESUME_DOWNLOAD", "Resume Download"),
                    ("PROJECT_LIVE_DEMO", "Project Live Demo"),
                    ("PROJECT_GITHUB", "Project GitHub"),
                    ("EMAIL_CLICK", "Email Click"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="License",
        ),
        migrations.DeleteModel(
            name="LicenseCategory",
        ),
    ]
