# Generated by Django 5.2.7 on 2025-10-08 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_remove_generalinfo_licenses_section_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clickevent",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="click_events",
                to="portfolio.project",
            ),
        ),
        migrations.AlterField(
            model_name="clickevent",
            name="details",
            field=models.CharField(
                blank=True,
                help_text="e.g., Project ID or other info",
                max_length=255,
                null=True,
            ),
        ),
    ]
